version: '3.5'

services:
  grafana:
    image: grafana/grafana:6.1.6
    volumes:
      - grafana_data:/var/lib/grafana
      - ./../configs/grafana/provisioning/:/etc/grafana/provisioning/
      - ./../configs/grafana/grafana.ini:/etc/grafana/grafana.ini
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m
    networks:
      - kaabah-network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.backend=grafana"
        - "traefik.enable=true"      
        - "traefik.docker.network=kaabah-network"
        - "traefik.port=3000"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.auth.basic=${AUTH_USER}:${AUTH_PASSWORD}"
        - "traefik.frontend.rule=Host:grafana.${SUBDOMAIN}"
      restart_policy:
        condition: on-failure

volumes:
  grafana_data: {}

networks:
  kaabah-network:
    name: ${DOCKER_NETWORK}
    external: true
    
